server:
  port: 1112
spring:
  application:
    name: consumer
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.example.consumer.rider.RiderLocation
#        spring.json.use.type.headers: false
  cloud:
    stream:
      function:
        definition: processRiderLocation
      bindings:
        processRiderLocation-in-0:
          destination: my-topic-new
      kafka:
        binder:
          brokers: localhost:9092